### PR TITLE
remove obsolete files

### PR DESCRIPTION
**Pull request by HerrMuellerluedenscheid**
I didn't find these files being used. So I removed them.

### CODE REVIEW

**Comment by priv-kweihmann** [comment]
These files basically act as an example for custom rules - I would rather leave them in here and add more documentation to it

**Comment by priv-kweihmann** [comment]
Added a reference to these files with https://github.com/priv-kweihmann/oelint-adv/commit/963cd2ef54303209cfe0082a01f152f9f2f5bbe0

**Comment by HerrMuellerluedenscheid** [comment]
It's still 100% redundant with the example privided in the README. The name of the module as well as the name of the folder is misleading. How about renaming that to `docs/rule_foo.py` or `docs/rule_example.py` or `examples/foo_rule.py`?

That would make the purpose much clearer from the naming.

**Comment by HerrMuellerluedenscheid** [comment]
Also, if this serves as an example it should also provide an implementation of the fixing mechanism, as this is a feature where `oelint` has the biggest chance to really be outstanding.

**Comment by HerrMuellerluedenscheid** [comment]
Changed the structure just to get a feeling. WDYT @priv-kweihmann

**Comment by priv-kweihmann** [comment]
Works for me

**Pull request merged**
