### PR TITLE
--exit-zero argument to always return 0

### PR DESCRIPTION
**Pull request by offa**
Adds the `--exit-zero` argument which sets the exit code to ´0` (successful) even on found issues. Scenarios to do this are eg. CI builds where the results are evaluated in later stages.

### CODE REVIEW

**Comment by priv-kweihmann** [comment]
LGTM, but that needs a test case in https://github.com/priv-kweihmann/oelint-adv/blob/master/tests/test_class_integration.py as well. Shall I provide that, or you want to add that to this PR?

**Comment by offa** [comment]
Ah, thanks for the hint, I'm going to add them.

**Comment by offa** [comment]
This turned out more complicated than expected. While all other tests work on `run()`, `main()` is necessary here.

**Comment by priv-kweihmann** [comment]
> This turned out more complicated than expected. While all other tests work on `run()`, `main()` is necessary here.

True - for me it would be enough to just test if the new optional argument is accepted by argparse

**Review by priv-kweihmann — APPROVED** [review]

**Pull request merged**
