### PR TITLE
add color output option to oelint-adv

### PR DESCRIPTION
**Pull request by FrazerClews**
WIP for since I feel it could be better, seems to work with multiple files and the commits and messages will need amending

### CODE REVIEW

**Comment by priv-kweihmann** [comment]
As you already said it, maybe not the best solution.
I'm okay with the option and the usage of colorama as a dep.
But the actual coloring has to be done differently - I would suggest to insert the functionality into https://github.com/priv-kweihmann/oelint-adv/blob/d3c62bee06295fa105946b69857958aa5dfff446/oelint_adv/cls_rule.py#L21, like with the rule file support I pushed yesterday -- that would be a solution that would work for me

**Comment by FrazerClews** [comment]
> As you already said it, maybe not the best solution.
> I'm okay with the option and the usage of colorama as a dep.
> But the actual coloring has to be done differently - I would suggest to insert the functionality into
> 
> https://github.com/priv-kweihmann/oelint-adv/blob/d3c62bee06295fa105946b69857958aa5dfff446/oelint_adv/cls_rule.py#L21
> , like with the rule file support I pushed yesterday -- that would be a solution that would work for me

Yeah as it's extra steps in the execution, was trying to find a way too but couldn't at the time without major modifications, but should now. Thanks

**Comment by priv-kweihmann** [comment]
Could please resolve the finding mentioned by LGTM, then we good to go

**Comment by FrazerClews** [comment]
> Could please resolve the finding mentioned by LGTM, then we good to go

There is an odd bug with the ordering when colored, where it goes in order of what error appears first of you get what I mean, although I plan to fix this in another PR as I know how to fix it, but is also related to fixing the ordering bug when the number of lines is double digits

**Comment by priv-kweihmann** [comment]
Windows isn't supported (and I guess it never will be), as bitbake doesn't run on Windows anyway.
Just one more thing: could please update the README as well to showcase the newly added option, thx

**Comment by FrazerClews** [comment]
> Windows isn't supported (and I guess it never will be), as bitbake doesn't run on Windows anyway.
> Just one more thing: could please update the README as well to showcase the newly added option, thx

That's that I thought, just wanted to check just in case there's a rare use case of people using just the linter on Windows, could be a future patch. README updated

**Comment by priv-kweihmann** [comment]
> > Windows isn't supported (and I guess it never will be), as bitbake doesn't run on Windows anyway.
> > Just one more thing: could please update the README as well to showcase the newly added option, thx
> 
> That's that I thought, just wanted to check just in case there's a rare use case of people using just the linter on Windows, could be a future patch. README updated

Don't get me started on Windows;-) - We'll see - At least I haven't meet anyone from the yocto-verse, who does "work" on Windows - so that really not a priority

**Pull request merged**
