### PR TITLE
refactored module names

### PR DESCRIPTION
**Pull request by HerrMuellerluedenscheid**
I find these module names are more apropriate and descriptive.

`jetm` could be moved into `rules` as it's just another sub-categorie. WDYT @priv-kweihmann ?

### CODE REVIEW

**Comment by priv-kweihmann** [comment]
I like the idea, but I'm sorry we can't merge that as it is right now.
Simply out in the wild users have custom rules that import `cls_rule`, so we need at least to over a legacy interface (with a deprecation note) if we want to change things

**Comment by priv-kweihmann** [comment]
A proper plan to change these would be

- rename modules
- provide a legacy interface with a one-time warning that this interface will be deprecated
- update documenation
- create deprecation issues for all interfaces and plan them for an upcoming 4.x release

**Comment by HerrMuellerluedenscheid** [comment]
> I like the idea, but I'm sorry we can't merge that as it is right now. Simply out in the wild users have custom rules that import `cls_rule`, so we need at least to over a legacy interface (with a deprecation note) if we want to change things

I'd rather introduce a breaking change in the change log (which I don't think exists yet) and bump the major version. But I don't feel this will happen. So...

**Comment by priv-kweihmann** [comment]
One note regarding the integration of the jetm ruleset:
> These rules are sometimes contrary to OE-style-guide, so use them with caution.

from the documentation makes it clear that those rules have to be kept separate.
Overall aim of the default option rule set has to be to be as close as possible to the oe-styleguide.

The jetm set is only interesting to a very narrow subset of the users of the this tool, so I'd like to keep it as it is.

**Comment by priv-kweihmann** [comment]
> > I like the idea, but I'm sorry we can't merge that as it is right now. Simply out in the wild users have custom rules that import `cls_rule`, so we need at least to over a legacy interface (with a deprecation note) if we want to change things
> 
> I'd rather introduce a breaking change in the change log (which I don't think exists yet) and bump the major version. But I don't feel this will happen. So...

That would be also fine but would imply having a compatibility version in the rules (which is also not yet there).
Current way I image this tool to be used

Users always use the latest version (this is also the only one that gets full support here).
Breaking API changes (there have been already a few) will be marked a deprecated for a grave period.
After the grace period the legacy interfaces are removed and a major version bump is done.

As we need to support code that we don't even know about (custom rules) and most of the code is run in automated systems, we would break a lot of builds immediately and ruin a lot of peoples Monday morning :-).
The only way we could do this is with the help of multiple version branches - but for them I honestly don't have the capacity to support them

**Pull request closed without merging**
